### ISSUE TITLE
[Question] How do I make grep ignore directories?

### ISSUE THREAD

**Issue by Industrial** [yegappan/grep#1]
Hi!

I want grep to ignore certain directories like `.git` and `node_modules`.

I have configured `let g:Grep_Default_Options="--exclude-dir=node_modules"` but that doesn't work.

**Comment by johnzeng** [comment]
I have the same issue , it says it can skip some file by setting Grep_Skip_Files, but it's not working for me. I don't sure if the owner is still working with this repo because it haven't update for like 3 years.

**Comment by DouglasOY** [comment]
hi, 

maybe I know this problem.
the root cause is the special usage of --exclude-dir.

# --exclude-dir usage:

example:
grep -rn "xyz" --exclude-dir=PATTERN  TARGET_DIR

two notes: 

# first -- do not append forward slash in the end of PATTERN

PATTERN is a string for a directory which can looks like, aa, aa/bb, aa/bb/cc.
but not append '/' to the string, which will like aa/, aa/bb/, aa/bb/cc/.

# second -- do not add prefix TARGET_DIR in the front of PATTERN

the results of example grep -rn "xyz" --exclude-dir=PATTERN  TARGET_DIR
will looks like:
TARGET_DIR/aa/bb/cc
TARGET_DIR/dd/ee/ff

so the PATTERN only works when it is in the subset of { aa/bb/cc,  dd/ee/ff}
if PATTERN is in the set of { TARGET_DIR/aa/bb/cc, TARGET_DIR/dd/ee/ff }, it does not work.

for instance:
if PATTERN is one of the following strings:
aa
bb
cc
aa/bb
bb/cc
aa/bb/cc

the result TARGET_DIR/aa/bb/cc/*\* will be filtered out.

if PATTERN is TARGET_DIR/aa
the result TARGET_DIR/aa/bb/cc/*\* will not be filtered out.

# conclusion

do not or as few as possible to use the option --exclude-dir 
it is weird.

**Comment by johnzeng** [comment]
@DouglasOY Hmm, I tried to remove the --exclude-dir option but still not working for me. I will have a try on how to fix it.
Actually it provide a Grep_Skip_Dirs and Grep_Skip_Files options, but none of them works.

**Comment by DouglasOY** [comment]
@Misfit-John  I looked at the code of grep.vim.
the  options  Grep_Skip_Dirs and Grep_Skip_Files  only used in the function RunGrepRecursive, so that only in the command started with "R" these options will work. 
these command are listed as follows:
Ragrep
RagrepAdd
Regrep
RegrepAdd
Rfgrep
RfgrepAdd
Rgrep
RgrepAdd

**Comment by johnzeng** [comment]
@DouglasOY Great Thanks, so I believe it's because we didn't use it in the right way, right?

**Comment by DouglasOY** [comment]
@Misfit-John  Yes. If you want to use Grep_Skip_Dirs and Grep_Skip_Files , you must use R_xx_grep command. In the command Grep, Bgrep, ..., these options do not work.

**Comment by johnzeng** [comment]
Hmm, I think I will fork this reop to my own git and update the doc, I see this owner is not working on git now. So...

**Comment by DouglasOY** [comment]
@Misfit-John  hi, I have tried Grep_Skip_Dirs in the command Rgrep, it didn't work also. Apparently, though the source code looks right.

**Comment by johnzeng** [comment]
@DouglasOY I just tried Regrep, it works. I don't sure about Rgrep

**Comment by DouglasOY** [comment]
yes,  you are right. the Rxxgrep commands are correct.

**Comment by yegappan** [comment]
Updated the help file to state that the Grep_Skip_Dirs and Grep_Skip_Files settings
are used only for recursive searches using the ":Rgrep", ":Rfgrep", ":Regrep" and
":Ragrep" commands.
